package com.zuowei.dao.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "BEAN".
 */
public class Bean {

    private String localId;
    private String content;
    private String className;
    private Integer commandType;
    private java.util.Date createAt;

    public Bean() {
    }

    public Bean(String localId) {
        this.localId = localId;
    }

    public Bean(String localId, String content, String className, Integer commandType, java.util.Date createAt) {
        this.localId = localId;
        this.content = content;
        this.className = className;
        this.commandType = commandType;
        this.createAt = createAt;
    }

    public String getLocalId() {
        return localId;
    }

    public void setLocalId(String localId) {
        this.localId = localId;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getClassName() {
        return className;
    }

    public void setClassName(String className) {
        this.className = className;
    }

    public Integer getCommandType() {
        return commandType;
    }

    public void setCommandType(Integer commandType) {
        this.commandType = commandType;
    }

    public java.util.Date getCreateAt() {
        return createAt;
    }

    public void setCreateAt(java.util.Date createAt) {
        this.createAt = createAt;
    }

}
