package com.zuowei.dao.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig schoolmateDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig beanDaoConfig;
    private final DaoConfig conversationDaoConfig;

    private final SchoolmateDao schoolmateDao;
    private final UserDao userDao;
    private final BeanDao beanDao;
    private final ConversationDao conversationDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        schoolmateDaoConfig = daoConfigMap.get(SchoolmateDao.class).clone();
        schoolmateDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        beanDaoConfig = daoConfigMap.get(BeanDao.class).clone();
        beanDaoConfig.initIdentityScope(type);

        conversationDaoConfig = daoConfigMap.get(ConversationDao.class).clone();
        conversationDaoConfig.initIdentityScope(type);

        schoolmateDao = new SchoolmateDao(schoolmateDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);
        beanDao = new BeanDao(beanDaoConfig, this);
        conversationDao = new ConversationDao(conversationDaoConfig, this);

        registerDao(Schoolmate.class, schoolmateDao);
        registerDao(User.class, userDao);
        registerDao(Bean.class, beanDao);
        registerDao(Conversation.class, conversationDao);
    }
    
    public void clear() {
        schoolmateDaoConfig.getIdentityScope().clear();
        userDaoConfig.getIdentityScope().clear();
        beanDaoConfig.getIdentityScope().clear();
        conversationDaoConfig.getIdentityScope().clear();
    }

    public SchoolmateDao getSchoolmateDao() {
        return schoolmateDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public BeanDao getBeanDao() {
        return beanDao;
    }

    public ConversationDao getConversationDao() {
        return conversationDao;
    }

}
