package com.zuowei.dao.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SCHOOLMATE".
 */
public class Schoolmate {

    private String userId;
    private Integer friendState;
    private java.util.Date createAt;

    public Schoolmate() {
    }

    public Schoolmate(String userId) {
        this.userId = userId;
    }

    public Schoolmate(String userId, Integer friendState, java.util.Date createAt) {
        this.userId = userId;
        this.friendState = friendState;
        this.createAt = createAt;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public Integer getFriendState() {
        return friendState;
    }

    public void setFriendState(Integer friendState) {
        this.friendState = friendState;
    }

    public java.util.Date getCreateAt() {
        return createAt;
    }

    public void setCreateAt(java.util.Date createAt) {
        this.createAt = createAt;
    }

}
