package com.zuowei.dao.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "USER".
 */
public class User {

    private String userName;
    private String nick;
    private String avatar;
    private String objectId;
    private String college;
    private Integer sex;
    private String interest;

    public User() {
    }

    public User(String userName) {
        this.userName = userName;
    }

    public User(String userName, String nick, String avatar, String objectId, String college, Integer sex, String interest) {
        this.userName = userName;
        this.nick = nick;
        this.avatar = avatar;
        this.objectId = objectId;
        this.college = college;
        this.sex = sex;
        this.interest = interest;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getNick() {
        return nick;
    }

    public void setNick(String nick) {
        this.nick = nick;
    }

    public String getAvatar() {
        return avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public String getObjectId() {
        return objectId;
    }

    public void setObjectId(String objectId) {
        this.objectId = objectId;
    }

    public String getCollege() {
        return college;
    }

    public void setCollege(String college) {
        this.college = college;
    }

    public Integer getSex() {
        return sex;
    }

    public void setSex(Integer sex) {
        this.sex = sex;
    }

    public String getInterest() {
        return interest;
    }

    public void setInterest(String interest) {
        this.interest = interest;
    }

    @Override
    public String toString() {
        return "User{" +
                "userName='" + userName + '\'' +
                ", nick='" + nick + '\'' +
                ", avatar='" + avatar + '\'' +
                ", objectId='" + objectId + '\'' +
                ", college='" + college + '\'' +
                ", sex=" + sex +
                ", interest='" + interest + '\'' +
                '}';
    }
}
